version: '2.1'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092-9094:9092"
    environment:
      HOSTNAME_COMMAND: "echo $$(hostname)"
      BROKER_ID_COMMAND: "docker inspect --format '{{ .Name }}' $$(hostname) | awk -F_ '{ printf $$NF }'"
      KAFKA_ADVERTISED_HOST_NAME: 127.24.18.81
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "Topic1:3:2,Topic2:2:2"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
#  es01:
#    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.2
#    container_name: es01
#    environment:
#      - node.name=es01
#      - discovery.seed_hosts=es02
#      - cluster.initial_master_nodes=es01,es02
#      - cluster.name=docker-cluster
#      - bootstrap.memory_lock=true
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    volumes:
#      - esdata01:/usr/share/elasticsearch/data
#    ports:
#      - 9200:9200
#    networks:
#      - esnet
#  es02:
#    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.2
#    container_name: es02
#    environment:
#      - node.name=es02
#      - discovery.seed_hosts=es01
#      - cluster.initial_master_nodes=es01,es02
#      - cluster.name=docker-cluster
#      - bootstrap.memory_lock=true
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    volumes:
#      - esdata02:/usr/share/elasticsearch/data
#    networks:
#      - esnet

#volumes:
#  esdata01:
#    driver: local
#  esdata02:
#    driver: local
#
#networks:
#  esnet:
